parameters:
   nazka_accesstoken_security.authentication_listener.class: Nazka\AccessTokenSecurityBundle\Security\Firewall\ApiListener
   nazka_accesstoken_security.authentication_manager.class: Nazka\AccessTokenSecurityBundle\Manager\AuthenticationManager
   nazka_accesstoken_security.token_provider.class: Nazka\AccessTokenSecurityBundle\Security\Authentication\Provider\AccessTokenProvider
   nazka_accesstoken_security.usernamepassword.login.manager.class: Nazka\AccessTokenSecurityBundle\Manager\UsernamePasswordLoginManager
   nazka_accesstoken_security.provider_key: api

services:
   nazka_accesstoken_security.authentication.listener:
        class:  %nazka_accesstoken_security.authentication_listener.class%
        arguments: [@security.context, @nazka_accesstoken_security.authentication.manager, %nazka_accesstoken_security.provider_key%]

   nazka_accesstoken_security.authentication.manager:
        class:  %nazka_accesstoken_security.authentication_manager.class%
        arguments: [@nazka_accesstoken_security.access_token.provider ]

   nazka_accesstoken_security.access_token.provider:
        class:  %nazka_accesstoken_security.token_provider.class%
        arguments: [@snc_redis.default, %nazka_accesstoken_security.provider_key%]
        
   nazka_accesstoken_security.usernamepassword.login.manager:
        class:  %nazka_accesstoken_security.usernamepassword.login.manager.class%
        arguments: [@security.authentication.manager, %nazka_accesstoken_security.usernamepassword.provider_key%]
        


